from pydantic import BaseModel, Field

class AgentRequest(BaseModel):
    instruction: str = Field(..., description="Instruction or message for the agent.")

class AgentResponse(BaseModel):
    status: str = Field(..., description="Processing result status.")
    output: str = Field(..., description="Response generated by the agent.")